image: registry.gitlab.com/brinkervii/grapejuice-ci-image/master

stages:
    - test
    - package
    - deploy
    - release

grapejuice:quality_control:
    stage: test
    script:
        - export PYTHONPATH=$(pwd)/src
        - python3 -m venv ./venv
        - ./venv/bin/python3 -m pip install -r requirements.dev.txt
        - ./venv/bin/python3 -m pip install -r requirements.txt
        - ./venv/bin/python3 -m pylint src
        - ./venv/bin/python3 -m pytest tests

grapejuice:test_local_installation:
    stage: test
    script:
        - ./install.py

grapejuice:linux_package:
    stage: package
    artifacts:
        expire_in: 1 week
        paths:
            - artifacts/
    script:
        - export PYTHONPATH=$(pwd)/src
        - python3 -m venv ./venv
        - ./venv/bin/python3 -m pip install -r requirements.dev.txt
        - ./venv/bin/python3 -m pip install -r requirements.txt
        - ./venv/bin/python3 -m grapejuice_packaging linux_package --dist-dir artifacts/linux_package
    only:
        - master
        - staging
        - develop

grapejuice:debian_package:
    stage: package
    artifacts:
        expire_in: 1 week
        paths:
            - artifacts/
    script:
        - export PYTHONPATH=$(pwd)/src
        - python3 -m grapejuice_packaging debian_package --dist-dir artifacts/debian_package
    only:
        - master
        - staging
        - develop

pages:
    stage: deploy
    artifacts:
        paths:
            - public
    script:
        - pushd ./documentation
        - pnpm install
        - pnpm build
        - popd
        - mkdir public
        - cp -frax ./documentation/dist/* ./public
        - bash ./ci_scripts/update_repositories.sh
        - python3 documentation/make-sitemap.py Grapejuice public
        - mv sitemap.html public/sitemap.html
        - ls -hal public
    cache:
        - key:
              files:
                  - documentation/pnpm-lock.yaml
          paths:
              - documentation/node_modules
    only:
        - master

make_release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - echo "Running the release job."
    release:
        name: "Release $CI_COMMIT_TAG"
        description: "Release created using the release-cli."
        tag_name: "$CI_COMMIT_TAG"
        ref: "$CI_COMMIT_TAG"
